[server]
enableXsrfProtection = false
enableCORS = false

[theme]
primaryColor = "#BB86FC"  
backgroundColor = "#121212"  
secondaryBackgroundColor = "#1E1E1E"  
textColor = "#FFFFFF"  
font = "sans serif"  

[browser]
gatherUsageStats = false  

[client]
showSidebarNavigation = false  
